format:
  # How wide to allow formatted cmake files
  line_width: 200

  # How many spaces to tab for indent
  tab_size: 4

  # If true, separate flow control names from their parentheses with a space
  separate_ctrl_name_with_space: false

  # If true, separate function names from parentheses with a space
  separate_fn_name_with_space: false

  # If a statement is wrapped to more than one line, than dangle the closing
  # parenthesis on its own line.
  dangle_parens: true

markup:
  enable_markup: false
